<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.15</version>
    </parent>
    <groupId>com.openjiuwen</groupId>
    <artifactId>studio</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>studio</name>
    <description/>
    <modules>
        <module>studio-common</module>
        <module>studio-manager</module>
        <module>studio-manager-api</module>
        <module>studio-manager-service</module>
        <module>studio-runtime</module>
        <module>studio-runtime-api</module>
        <module>studio-runtime-service</module>
    </modules>

    <properties>
        <jdk.version>17</jdk.version>
        <obs.version>3.23.9</obs.version>
        <devspore.version>2.1.19-RELEASE</devspore.version>
        <revision>0.0.1</revision>
        <webflux-ui.version>1.6.9</webflux-ui.version>
        <fastjson2.version>2.0.51</fastjson2.version>
        <okhttp-sse.version>4.12.0</okhttp-sse.version>
        <annotation-api.version>3.0.0</annotation-api.version>
        <h2.version>2.2.224</h2.version>
        <plexus-archiver.version>4.11.0</plexus-archiver.version>
        <mariadb-java-client.version>3.5.6</mariadb-java-client.version>
        <swaggerV2.version>1.6.14</swaggerV2.version>
        <springdoc-openapi.version>2.8.8</springdoc-openapi.version>
        <jacoco.version>0.8.11</jacoco.version>
        <jacoco.skip>true</jacoco.skip>
        <pagehelper.version>6.1.0</pagehelper.version>
        <pagehelper-springboot.version>2.1.0</pagehelper-springboot.version>
        <spring.security.core.version>6.5.10</spring.security.core.version>
        <seccomponent.version>1.2.1a_hitls-rc.2</seccomponent.version>
        <item.alarm.version>3.0.0</item.alarm.version>
        <quartz.version>2.5.2</quartz.version>
        <commons.collections.version>4.5.0-M1</commons.collections.version>
        <quartz-springboot.version>3.5.15</quartz-springboot.version>
        <poi.version>5.4.0</poi.version>
        <swagger-parser.version>2.1.24</swagger-parser.version>
        <swagger-core.version>2.2.25</swagger-core.version>
        <jaxb.version>2.3.9</jaxb.version>
        <runtime.version>0.0.1-SNAPSHOT</runtime.version>
        <studio.common.version>1.19.3</studio.common.version>
        <jose4j.version>0.9.6</jose4j.version>
        <redisson.version>3.39.0</redisson.version>
        <mcp.sdk.version>0.16.0</mcp.sdk.version>
        <tomcat-embed-core.version>10.1.56</tomcat-embed-core.version>
        <hadoop.version>3.4.2</hadoop.version>
        <http.version>4.5.14</http.version>
        <org.jetbrains.version>26.0.1</org.jetbrains.version>
        <io-netty-version>4.1.133.Final</io-netty-version>
        <vpc-version>3.1.163</vpc-version>
        <swr-version>3.1.151</swr-version>
        <elb-version>3.1.125</elb-version>
        <eip-version>3.1.151</eip-version>
        <nat-version>3.1.151</nat-version>
        <hibernate.version>6.6.8.Final</hibernate.version>
        <hibernate-annotations.version>7.0.3.Final</hibernate-annotations.version>
        <hibernate-validator.version>8.0.2.Final</hibernate-validator.version>
        <org.opengauss.version>5.0.0-og</org.opengauss.version>
        <bcprov-jdk18on.version>1.84</bcprov-jdk18on.version>
        <avro.version>1.11.4</avro.version>
        <commons-lang3.version>3.18.0</commons-lang3.version>
        <httpclient5.version>5.4.4</httpclient5.version>
        <httpcore5.version>5.3</httpcore5.version>
        <nimbus-jose-jwt.version>10.3</nimbus-jose-jwt.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <jsqlparser.version>4.7</jsqlparser.version>
        <postgresql.version>42.7.11</postgresql.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.42</version>
        </dependency>
        <dependency>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
            <version>2.22.0</version>
        </dependency>
        <dependency>
            <artifactId>jackson-annotations</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
            <version>2.21</version>
        </dependency>
        <dependency>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <version>2.20.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.20.2</version>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <!--Hdt 使用离线模式依赖。-->
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>org.jacoco.agent</artifactId>
            <version>${jacoco.version}</version>
            <classifier>runtime</classifier>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nimbusds</groupId>
                <artifactId>nimbus-jose-jwt</artifactId>
                <version>${nimbus-jose-jwt.version}</version>
            </dependency>
            <!-- 统一 commons-lang3 版本 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>

            <!-- 统一 httpclient5 版本 -->
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${httpclient5.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-common</artifactId>
                <version>${hadoop.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-io</groupId>
                        <artifactId>commons-io</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.bouncycastle</groupId>
                        <artifactId>bcprov-jdk15on</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-reload4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>ch.qos.reload4j</groupId>
                        <artifactId>reload4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-server</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-servlet</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-util</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.eclipse.jetty</groupId>
                        <artifactId>jetty-webapp</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>${avro.version}</version>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-handler</artifactId>
                <version>4.1.135.Final</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${tomcat-embed-core.version}</version>
            </dependency>
            <dependency>
                <groupId>joda-time</groupId>
                <artifactId>joda-time</artifactId>
                <version>2.12.7</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okio</groupId>
                <artifactId>okio-jvm</artifactId>
                <version>3.6.0</version>
            </dependency>
            <dependency>
                <groupId>org.wiremock</groupId>
                <artifactId>wiremock</artifactId>
                <version>3.0.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-bom</artifactId>
                <version>11.0.15</version>
                <type>pom</type>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${io-netty-version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.xmlbeans</groupId>
                <artifactId>xmlbeans</artifactId>
                <version>5.2.1</version>
            </dependency>
            <dependency>
                <groupId>com.huaweicloud</groupId>
                <artifactId>esdk-obs-java</artifactId>
                <version>${obs.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>${jsqlparser.version}</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.plexus</groupId>
                <artifactId>plexus-archiver</artifactId>
                <version>${plexus-archiver.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>
                        <arg>-nowarn</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco.version}</version>
                <configuration>
                    <skip>${jacoco.skip}</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                    <argLine>@{argLine} -Dfile.encoding=UTF-8</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
