# -*- coding:utf-8 -*-
#  Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
from dataclasses import dataclass

from agent_builder.agent_evolving.agent_rl.src.runtime_and_sampler_adaptor.base import (
    Rollout,
)


@dataclass
class RewardInput:
    """
    rollout_list: List of rollout objects generated by the model for a single prompt.
    label: Ground-truth answer used to compute reward scores.
    """

    rollout_list: list[Rollout]
    label: str


@dataclass
class RewardResult:
    """
    global_reward: Overall reward value for the entire rollout sequence.
    reward_list: Step-level reward scores aligned with rollout_list.
    """

    global_reward: float
    reward_list: list[float]


class RewardCaller:
    """
    Wrapper for invoking reward functions, using either a local implementation
    or an optional remote HTTP API based on the provided RewardInput.
    """

    def __init__(self, reward_fn: callable = None):
        """
        Initialize the reward caller.

        Args:
            reward_fn: callable(rollout_list, label) -> (global_reward, reward_list)
        """
        if reward_fn is None:
            raise ValueError("reward_fn must be provided")

        self.reward_fn = reward_fn

    def compute_reward(self, reward_input: RewardInput) -> RewardResult:
        """
        Compute reward using local reward function.

        Input:
            RewardInput.rollout_list: list[Rollout]
            RewardInput.label: str

        Output:
            RewardResult.global_reward: float
            RewardResult.reward_list: list[float]
        """
        pass
