# ==========================================云服务私有配置项start=====================================
server:
  port: 31113
  address: ${server_ip:0.0.0.0}
  max-http-request-header-size: 100KB
  ssl:
    client-auth: none
    protocol: TLS
    # 支持TLS1.3的java版本，可以配置为：TLSv1.3,TLSv1.2
    enabled-protocols: TLSv1.2
    # 默认配置支持的算法为安全推荐的算法
    # 支持TLS1.3的java版本，可以配置为：TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    ciphers: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    key-password: ${server_ssl_key_password}
    key-store: ${APP_PATH:/opt/cloud/studio-service}/ssl/server.keystore
    key-store-password: ${server_ssl_key_store_password}
    key-store-type: jks
    trust-store: ${APP_PATH:/opt/cloud/studio-service}/ssl/trust.keystore
    trust-store-password: ${server_ssl_trust_store_password}
    trust-store-type: JKS
    # 是否开启ssl
    enabled: ${server_ssl_enabled:false}
  tomcat:
    max-http-response-header-size: 16KB
    accesslog:
      enabled: ${tomcat_access_enable:false}
      pattern: '%t %a "%r" %s (%D ms)'
      directory: /opt/cloud/logs/agent-builder-agent-runtime
      prefix: access
      file-date-format: .yyyy-MM-dd
      rotate: true
      buffered: true

    threads:
      max: ${tomcat_threads_max:400}
      min-spare: ${tomcat_threads_min_spare:40}

spring:
  servlet:
    multipart:
      max-file-size: ${spring_servlet_multipart_max_file_size:128MB}
      max-request-size: ${spring_servlet_multipart_max_request_size:128MB}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${spring_datasource_url:}
    username: ${spring_datasource_username:}
    password: ${spring_datasource_password:}
    driver-class-name: ${spring_datasource_driver_class_name:org.mariadb.jdbc.Driver}
    hikari:
      initialization-fail-timeout: -1  # 禁用启动时的连接检查
  sql:
    init:
      encoding: UTF-8
      schema-locations: classpath:sql/init.sql
      data-locations: classpath:sql/init_data.sql
      mode: ${spring_sql_init_mode:always}
      continue-on-error: true
  h2:
    console:
      enabled: false
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: non_null
  # 线程池配置
  pools:
    asyncExecutor:
      corePoolSize: ${agent_settings_pools_asyncExecutor_corePoolSize:10}
      maxPoolSize: ${agent_settings_pools_asyncExecutor_maxPoolSize:100}
      queueCapacity: ${agent_settings_pools_asyncExecutor_queueCapacity:10}
      threadNamePrefix: asyncExecutor-
      keepAliveSeconds: ${agent_settings_pools_asyncExecutor_keepAliveSeconds:60}
  data:
    redis:
      host: ${redis_host:127.0.0.1}
      port: ${redis_port:6379}
      password: ${redis_password:}

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  type-handlers-package: com.openjiuwen.studio.agent.runtime.mapper.handler

mybatis-plus:
  configuration:
    log-impl: ${mybatis_log_impl:org.apache.ibatis.logging.nologging.NoLoggingImpl}
  global-config:
    db-config:
      id-type: auto # 全局默认主键策略设置为数据库自增
      db-type: mysql
redis:
  host: ${redis_host:127.0.0.1}
  password: ${redis_password:}
  port: ${redis_port:6379}
  expire_time: ${redis_expire_time:604800}
  max_message_num: ${redis_max_message_num:100}
  max_message_size: ${max_message_size:5000000}
  max_debug_msg_size: ${max_debug_msg_size:10000}
  database: 0
  user-variables-expire-time: ${redis_user_variables_expire_time:31536000}
  conversation-variables-expire-time: ${redis_conversation_variables_expire_time:604800}
  node_addr_list: ${redis_node_addr_list:}
  master: ${redis_master_name:mymaster}
  sentinel_ports: ${redis_sentinel_ports:26800,26801}
  target_ports: ${redis_target_ports:16800,16801}
  cluster_node_list: ${cluster_node_list:}
  client-type: ${redis_client_type:redisson}
  enable-log: ${redis_enable_log:false}

# 委托换取token
delegate:
  token:
    itep-dispatcher-endpoint: ${itep_dispatcher_endpoint:}
    agency-token-url: ${agency_token_url:}

# health check
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: none # Web 端不暴露任何端点（核心）

lite:
  api-code:
    enabled: ${lite_api_code_enabled:false}

obs:
  url: ${obs_url:}
  ak: ${obs_ak:}
  sk: ${obs_sk:}
  bucket: ${obs_bucket:}
  staging-bucket: ${obs_staging_bucket:agent-builder-files-staging}
  opensource: ${obs_opensource:true}
  expire-time: ${obs_expire_time:7}
  bucket_storage_limit: ${obs_bucket_storage_limit:100}
  path:
    style: ${DATASOURCE_OBS_PATH_STYLE:path}

iam:
  url: ${iam_endpoint:}
  user:
    name: ${iam_user_name:}
    password: ${iam_user_password:}
    domain: ${iam_user_domain:}
  project:
    name: ${iam_project_name:}
    id: ${op_svc_project_id:}
  assumeRole:
    agencyName: ${iam_assumeRole_agencyName:}

env:
  type: simple

op:
  svc:
    project-id: ${op_svc_project_id:op_svc_project_mock}
    cross-region-project-id: ${op_svc_cross_region_project_id:op_svc_project_mock}

tool:
  request:
    timeout: ${tool_request_timeout:300}
    max-image-size: ${max-image-size:3145728}
  url:
    enable-check: ${enable_tool_url_check:false}
    black-list: ${tool_url_black_list:}
    white-list: ${tool_url_white_list:}
okhttp:
  ignore-cert: ${okhttp_ignore_cert:true}
  max-idle-connections: ${okhttp_max_idle_connections:40}
  keep-alive-duration: ${okhttp_keep_alive_duration:30}
  connect-timeout: ${okhttp_connect_timeout:10}
  wait-timeout: ${okhttp_wait_timeout:10}
  read-timeout: ${okhttp_read_timeout:900}
  max-requests-perhost: ${okhttp_max-requests-perhost:400}
  max-requests: ${okhttp_max-requests:400}

memory:
  chunk-num: ${memory_chunk_num:10}
  conversation-num: ${memory_conversation_num:4}

feedback:
  backflow-enabled: ${feedback_backflow_enabled:false}
  backflow-interval-ms: ${feedback_backflow_interval_ms:1800000}
  backflow-clear-cron-expression: ${feedback_backflow_clear_cron_expression:0 0 0 * * ?}

file:
  img-type: ${file_img_type:.png,.jpg,.jpeg,.bmp,.gif}
  video-type: ${file_video_type:.mp4,.avi,.mov,.wmv,.flv}
  icon-type: ${file_icon_type:.jpg,.jpeg,.png,.gif}
  import-type: ${file_import_type:.jsonl}
  default-type: ${file_default_type:.doc,.docx,.txt,.pdf,.csv,.xlsx,.xls,.pptx,.ppt,.png,.jpg,.jpeg,.bmp,.gif,.mp3,.mp4,.wav,.amr,.m4a,.ogg,.flac,.webm,.aac,.ac3,.mov,.wma,.avi,.rmvb,.mkv,.flv,.f4v,.wmv,.3gp,.jsonl}
  max-upload-num: ${max_upload_num:20}
  time-scope-upload-num: ${time_scope_upload_num:300}
  max-upload-total-size: ${max_upload_total_size:204800}
  time-scope-upload-total-size: ${time_scope_upload_total_size:86400}
  readonly:
    enable: ${file_readonly_enable:false}
  access:
    expiration-minutes: ${file_upload_expiration_minutes:10080}

icon:
  max-size: ${icon_max_size:200}

# openfeign配置
feign:
  client:
    config:
      iamManager:
        url: ${iam_manager_endpoint:http://mock-iam-manager:8080}
      agentManager:
        url: ${agent_manager_endpoint:http://127.0.0.1:31111}
      kooSearch:
        url: ${koosearch_endpoint:http://mock-koo-search:8080}
      jiuWenService:
        url: ${jiuwen_base_url:http://127.0.0.1:31014}
      modelManager:
        url: ${model_manager_endpoint:http://mock-model-manager:8080}
      ocrClient:
        url: ${ocr_endpoint:http://mock-ocr:8080}
      sisClient:
        url: ${sis_endpoint:http://mock-sis:8080}
      uniFactory:
        url: ${uniFactory_endpoint:http://mock-uni-factory:8080}
      dataManager:
        url: ${data_manager_endpoint:http://mock-data-manager:8080}
      userAuth:
        url: ${user_auth_endpoint:http://127.0.0.1:31113}
# ==================================== jiuwen配置 begin =========================================
jiuwen:
  base-url: ${jiuwen_base_url:}
  deep-research-url: ${jiuwen_deep_research_url:}
  run-api: ${jiuwen_run_api:/v1/orchestration/ir/execute}
  node-execute-api: ${jiuwen_node_execute_api:/v1/orchestration/ir/component/%s/execute}
  model-params: ${jiuwen_model_params:{}}
  prompt-builder: ${prompt_builder_url:/v1/prompt/build}
# ==================================== jiuwen配置 end =========================================

# ==================================== AgentOps配置 begin =========================================
agent-ops:
  default-mode: ${agent_ops_default_mode:API}
  enable: ${agent_ops_enable:false}
  base-url: ${agent_ops_base_url:https://localhost:8080}
  trace-api: ${agent_ops_trace_api:/ops/openapi/v2/trace}
  session-api: ${agent_ops_session_api:/ops/openapi/v1/session}
  core-pool-size: ${agent_ops_core_pool_size:8}
  max-pool-size: ${agent_ops_max_pool_size:32}
  pool-keep-alive: ${agent_ops_pool_keep_alive:60}
# ==================================== AgentOps配置 end =========================================

# ==================================== workflow配置 begin =========================================
workflow:
  ir-obs-path: ${workflow_ir_obs_path:workflow/ir}
  ir-cache-hours: ${workflow_ir_cache_in_hours:1}
  sse-timeout-milliseconds: ${workflow_sse_timeout_milliseconds:900000}
  max-query-length: ${workflow_max_query_length:100000}
  insight-exec-rel: ${workflow_insight_exec_rel:insight_exec_rel_%s_%s_%s}
  insight-conv-rel: ${workflow_insight_conv_rel:insight_conv_%s_%s}
  insight-exec: ${workflow_insight_exec:insight_exec_%s_%s}
  instance-expire: ${workflow_instance_expire:10}
  conversation-expire: ${workflow_conversation_expire:7}
  max-conversation-size: ${workflow_max_conversation_size:20}
  max-execution-size: ${workflow_max_execution_size:20}
  run-interface:
    timeout: ${workflow_run_interface_timeout:900}
  log-event: ${workflow_log_event:START,WORKFLOW_START,DONE,WORKFLOW_END}
  connector_config_host_blacklist: ${host_blacklist:}
  connector_config_host_whitelist: ${host_whitelist:}
  finish-keep-text: ${finish_keep_text:false}
# ==================================== workflow配置 end =========================================

# ==================================== 知识型agent配置 begin =========================================
agent:
  ir-obs-path: ${agent_ir_obs_path:agent/ir}
  ir-cache-hours: ${agent_ir_cache_in_hours:1}
  max-query-length: ${agent_max_query_length:100000}
  max-deep-research-message-length: ${deep_research_max_message_length:20000}
  sse-timeout-milliseconds: ${agent_sse_timeout_milliseconds:900000}
  deep-research-sse-timeout-milliseconds: ${deep_research_sse_timeout_milliseconds:7200000}
  jiuwen-timeout-milliseconds: ${agent_jiuwen_timeout_milliseconds:900000}
  insight-conv-rel: ${agent_insight_conv_rel:insight_conv_%s_%s}
  insight-exec-rel: ${agent_insight_exec_rel:insight_exec_rel_%s_%s_%s}
  insight-exec: ${agent_insight_exec:insight_exec_%s_%s}
  max-conversation-size: ${agent_max_conversation_size:50}
  max-execution-size: ${agent_max_execution_size:20}
  max-resolve-size: ${agent_max_resolve_size:5000}
  max-resolve-file-number: ${agent_max_resolve_file_number:10}
  max-upload-file-size: ${agent_max_upload_file_size:131072}
  max-upload-image-size: ${agent_max_upload_image_size:5120}
  conversion_file_max_num: ${conversion_file_max_num:10}
  finish-keep-text: ${finish_keep_text:false}
  skill-enabled: ${skill_enabled:true}
# ==================================== 知识型agent配置 end =========================================

# ==================================== 知识库配置 begin =========================================
knowledge:
  retrieve-merging-strategy: ${knowledge_retrieve_merging_strategy:KooSearchScoreMergingStrategy}
  source: ${knowledge_source:LakeSearch}
  bound:
    limit: ${knowledge_bound_limit:3}
  lakeSearch:
    auth-mode: ${knowledge_lakeSearch_auth_mode:none}
    endpoint: ${knowledge_lakeSearch_endpoint:http://127.0.0.1}
    project-id: ${knowledge_lakeSearch_project_id:}
    application-id: ${knowledge_lakeSearch_application_id:}
  retrieval-image-validity-days: ${knowledge_retrieval_image_validity_days:7}
# ==================================== 知识库配置 end =========================================

# ==================================== 内容审核配置 begin =========================================
sensitive:
  buffer:
    length: ${sensitive_buffer_length:1}
# ==================================== 内容审核配置 end =========================================

# ==================================== 公共配置 begin =========================================
release:
  web-rel: ${release_web_rel:release_web_rel_%s}
  app-rel: ${release_app_rel:release_app_rel_%s_%s}
  cloud-rel: ${release_cloud_rel:release_cloud_rel_%s}

model:
  invoke:
    debug: ${model_invoke_debug_log:false}
  video:
    task:
      keep-time: ${video_generation_task_keep_time:604800}
  platform:
    provider: ${platform_provider:100}
  security:
    report: ${model_chat_content_report:false}
    allreport: ${model_chat_content_allreport:false}
    record:
      pathPrefix: ${model_chat_content_path:chat/contents/}
      keepNum: ${model_chat_keepnum:200}
      localPath: ${model_chat_local_path:/opt/cloud/logs/agent-builder-agent-runtime/tmp}
  prompt-build:
    id: ${prompt_build_model_id:}
    type: ${prompt_build_model_type:openai}

  request:
    timeout: ${model_request_time:900000}
    connection-timeout: ${model_connection_timeout:10000}
    maxTotal: ${model_request_max_total:200}
    defaultMaxPerRoute: ${model_request_max_pre_route:50}
    thread:
      corePoolSize: ${model_invoke_thread_core_pool:150}
      maxPoolSize: ${model_invoke_thread_max_pool:500}
      queueCapacity: ${model_invoke_thread_core:50}

    securityCheck: ${model_request_security_check:true}
    proxy:
      open: ${model_request_proxy_open:false}
      user: ${model_request_proxy_user:}
      password: ${model_request_proxy_pwd:}
      host: ${model_request_proxy_host:}
      no-host: ${model_request_proxy_no_host:}
      port: ${model_request_proxy_port:8080}

task:
  async:
    pool-size: ${task_async_pool_size:100}
    execute-cron-expression: ${task_async_execute_cron_expression:0/30 * * * * ?}
    expire-days: ${task_async_expire_days:7}
    clear-cron-expression: ${task_async_clear_cron_expression:0 0 2 */7 * ?}
    max-execute-milliseconds: ${task_async_max_execute_milliseconds:172800000}
    execute-lock-key: ${task_async_execute_lock_key:async_execute_lock}
    clear-lock-key: ${task_async_clear_lock_key:async_clear_lock}
# ==================================== 公共配置 end =========================================


# ==================================== 流式接口心跳事件配置 start ===============================
heartbeat:
  pool-size: ${heartbeat_pool_size:150}
  interval-seconds: ${heartbeat_interval_seconds:10}
  # 开关模式: always,debug,off
  switch-mode: ${heartbeat_switch_mode:debug}
# ==================================== 流式接口心跳事件配置 end ===============================

log:
  mask: ${log_mask:true}
moderation:
  endpoint: ${moderation_endpoint:}
  enable: ${moderation_enable:false}
  source_id: ${moderation_source_id:94ea75dd-acd8-4399-80ed-fb7c7d8d93af}
  shareValue: ${moderation_share_value:default}
  glossary:
    white_list: ${moderation_glossary_white_list:agent-builder_white_glossary}
    black_list: ${moderation_glossary_black_list:verstile_black_glossary_ad,verstile_black_glossary_abuse,verstile_black_glossary_ban,verstile_black_glossary_porn,verstile_black_glossary_terrorism,verstile_black_glossary_politics}
dmq:
  client_id: 202500037
wiseagent:
  deployment:
    scene: HCS

license:
  ctrl:
    enable: ${license_ctrl_enable:false}
  apiInvocation:
    ctrl:
      enable: ${license_api_invocation_ctrl_enable:false}
    attrCode: ${license_api_invocation_attr_code:agent_api_invocation_count}
  cache:
    expireTimeS: ${license_api_invocation_cache_expire_time_s:600}

runtime:
  health:
    content: ${health_content:success}

# =============== 轻量化版本 =========================
poc:
  user:
    default-user-id: testUser
    default-project-id: 0
    default-domain-id: 0
# =============== 轻量化版本 =========================

tenant:
  freeze:
    filter:
      # 是否开启被冻结租户的拦截
      enabled: ${freeze_filter_enable:false}
      # 当前服务不需要进行拦截的接口API，使用url通配符进行处理
      white_list: ${freeze_filter_white_list:/v1/common-intern/kms/**,/v1/common/kms/**,/v1/common/tenant/*/query,/v1/common-console/subscribe/sync,/v1/common/license/query-resource-insts,/v1/common/license/query,/v1/common/license/report,/manager/inner/**}
  get:
    black_list: ${tenant_get_black_list:}
  post:
    white_list: ${tenant_post_white_list:/v1/[a-fA-F0-9]+/ops/statistic/config,/v1/[a-fA-F0-9]+/mcp/server/list,/v1/[a-fA-F0-9]+/mcp/service/list,/v1/[a-fA-F0-9]+/agent-builder/prompt-engineering/template/list,/v1/[a-fA-F0-9]+/agent-manager/workspace/init}
  put:
    white_list: ${tenant_put_white_list:}
  delete:
    white_list: ${tenant_delete_white_list:}

# AgentBuilderCommonSDK中调用agent-manager服务的地址
agent-builder:
  agent-manager:
    domain: ${agent_manager_endpoint:http://127.0.0.1:31111}

isHcs: ${is_hcs:false}
trace.audit.enabled: false

alarm:
  log-enable: ${alarm_log_enable:false}

# 域名校验
host-validation:
  enabled: ${host-validation_enabled:true}
  pattern: ${host-validation_pattern:}
  pattern-group: ${host-validation_pattern_group:1}

rest.client.enabled: false

system:
  crypt:
    # 系统默认的加解密方式，NO_OP_CIPHER-表示不加密
    name: ${system_crypt_name:NO_OP_CIPHER}